2018-05-18T05:45:02.726Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The current identity, with the name 'admin' and the identifier '01899e04161a3a6d64670504fa122e55818295352929b6a616333a3739fde3f2', must be activated (ACTIVATION_REQUIRED)
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:45:02.727Z ERROR   :HLFConnection            :ping()                    {"message":"Error trying to ping. Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The current identity, with the name 'admin' and the identifier '01899e04161a3a6d64670504fa122e55818295352929b6a616333a3739fde3f2', must be activated (ACTIVATION_REQUIRED)","stack":"Error: Error trying to ping. Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The current identity, with the name 'admin' and the identifier '01899e04161a3a6d64670504fa122e55818295352929b6a616333a3739fde3f2', must be activated (ACTIVATION_REQUIRED)\n    at _checkRuntimeVersions.then.catch (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-cli/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:790:34)\n    at <anonymous>"}$
2018-05-18T05:47:13.404Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:47:13.406Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:47:13.407Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:47:13.407Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:47:13.410Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:47:13.416Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:47:13.416Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:47:13.417Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:47:13.417Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:47:13.418Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:47:13.418Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:47:13.419Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:47:13.419Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:47:13.420Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:47:13.421Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:47:13.426Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:47:13.427Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Object with ID '1' in collection with ID 'Asset:org.maintenance.network.MachineDiagn' does not exist\n    at _initializeChannel.then.then.then.then.catch (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:957:34)\n    at <anonymous>"}$
2018-05-18T05:48:38.227Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:48:38.228Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:48:38.229Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:48:38.231Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:48:38.242Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:48:38.246Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:48:38.246Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:48:38.247Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:48:38.247Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:48:38.248Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:48:38.248Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:48:38.249Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:48:38.249Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:48:38.251Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:48:38.252Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:48:38.252Z ERROR   :HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists
    at new createStatusError (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:64:15)
    at /home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/grpc/src/client.js:583:15 {}$
2018-05-18T05:48:38.252Z ERROR   :HLFConnection            :invokeChainCode()         {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: Failed to add object with ID '7' in collection with ID 'Asset:org.maintenance.network.MachineProgn' as the object already exists\n    at _initializeChannel.then.then.then.then.catch (/home/ubuntu/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:957:34)\n    at <anonymous>"}$
